spring.application.name=leadgen-backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/leadgen
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=replace_with_secure_random_string
jwt.expiration-ms=3600000

# Server
server.port=8080

#Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

